
; platformio.ini
[platformio]
# Tell PlatformIO to extra-load parameters from your secret file if it exists
extra_configs = private.ini

[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
lib_deps = blynkkk/Blynk@^1.3.5

# Inject the build flags imported from extra_secrets directly into the compiler
build_flags = ${extra_secrets.build_flags}
